/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "part_b.h"
#include <fcntl.h>
#include <unistd.h>

void
blackbox_prog_1(char *host, int num1, int num2, char pathOfBlackbox[], char pathOfOutput[])
{
	CLIENT *clnt;
	char * *result_1;
	numbers  blackbox_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, BLACKBOX_PROG, BLACKBOX_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	blackbox_1_arg.a = num1;
	blackbox_1_arg.b = num2;
	memset(blackbox_1_arg.pathOfBlackbox, '\0', sizeof(blackbox_1_arg.pathOfBlackbox));
	strcpy(blackbox_1_arg.pathOfBlackbox, pathOfBlackbox);   
	result_1 = blackbox_1(&blackbox_1_arg, clnt);
	
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}

	int output = open(pathOfOutput, O_APPEND|O_WRONLY|O_CREAT, 0744);
	int status = write(output, *result_1, strlen(*result_1));
    
    if(status < 0){
      printf("%s\n", "cannot write");
    }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int num1, num2;
	if (argc < 4) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[3];
	char* pathOfBlackbox = argv[1];
	char* pathOfOutput = argv[2];
	scanf("%d", &num1);
	scanf("%d", &num2);
	blackbox_prog_1 (host, num1, num2, pathOfBlackbox, pathOfOutput);
exit (0);
}
